services:
  app:
    build: ./docker/app
    volumes:
      - ../:/workspace:cached
    tty: true
    environment:
      PHP_EXTENSION_XDEBUG: 1
      XDEBUG_MODE: "debug,develop"
      XDEBUG_CONFIG: "client_port=9003 client_host=localhost"
